---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: webserver1
  name: webserver1-deployment
  labels:
    app: webserverprod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webserverprod
  template:
    metadata:
      labels:
        app: webserverprod
    spec:
      containers:
        - image: 244857349068.dkr.ecr.ap-east-1.amazonaws.com/cicdwebserver1:latest
          name: webserver1-node
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: webserver1
  name: webserver1-service
spec:
  selector:
    app: webserverprod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
